name: Karate Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Add Execution Permission
        run: chmod +x mvnw

      - name: Build and Test with Maven
        run: |
          ./mvnw clean test -Dtest="TestRunner#testScenario"

      - name: Deploy Karate HTML Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GH_TKN }}
          publish_dir: ./target/karate-reports